language: python
python: 3.9
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.6
      - python3.6-dev
      - python3.7
      - python3.7-dev
      - python3.8
      - python3.8-dev

install: pip install tox

env:
  matrix:
    # consul 0.7.5
    - TOX_ENV=py27     CONSUL_VERSION=0.7.5

    # consul 0.8.5
    - TOX_ENV=py27     CONSUL_VERSION=0.8.5
    - TOX_ENV=py36     CONSUL_VERSION=0.8.5
    - TOX_ENV=py37     CONSUL_VERSION=0.8.5
    - TOX_ENV=py38     CONSUL_VERSION=0.8.5
    - TOX_ENV=py39     CONSUL_VERSION=0.8.5

    # consul 0.9.0
    - TOX_ENV=py27     CONSUL_VERSION=0.9.0
    - TOX_ENV=py36     CONSUL_VERSION=0.9.0
    - TOX_ENV=py37     CONSUL_VERSION=0.9.0
    - TOX_ENV=py38     CONSUL_VERSION=0.9.0
    - TOX_ENV=py39     CONSUL_VERSION=0.9.0

    # coverage and style checks
    - TOX_ENV=pep8     CONSUL_VERSION=0.9.0
    - TOX_ENV=coverage CONSUL_VERSION=0.9.0

before_script:
  - wget https://releases.hashicorp.com/consul/${CONSUL_VERSION}/consul_${CONSUL_VERSION}_linux_amd64.zip
  - unzip consul_${CONSUL_VERSION}_linux_amd64.zip
  - start-stop-daemon --start --background --exec ${TRAVIS_BUILD_DIR}/consul -- agent -server -data-dir /tmp/consul -bootstrap-expect=1 -bind=127.0.0.1

script:
  - tox -e $TOX_ENV

notifications:
  email:
    - tetsuya.morimoto@gmail.com
